<? php
echo '<!DOCTYPE html>';
echo '<html lang="fr">';
echo '<head>';
echo '<meta charset="utf-8">';
echo '<title>Home :: iPhoenix42's Website</title>';
echo '<base target="_top">';
echo '<link href="../Resources/jonyive.css" rel="stylesheet">';
echo '<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">';
echo '<link rel="shortcut icon" href="../Resources/iPhoenixlogo.png">';
echo '</head>';
echo '<body class="iOS">';
echo '<panel>';
echo '<fieldset style="background-color: #CC0000">';
echo '<a href="?">';
echo '<img class="icon" src="../Resources/CydiaIcon.png">';
echo '<div>';
echo '<label>iPhoenix42's Website</label>';
echo '</div>';
echo '</a>';
echo '</fieldset>';
echo '<panel>';
echo '<fieldset style="background-color: transparent; border: none; margin: -4px 10px -14px 10px">';
echo '<div>';
echo '<div style="float: right; margin-top: 7px; text-align: center; width: 200px">';
echo '<span style="font-size: 20px" id="welcome">iPhoenix42's Website</span><br/>';
echo '<span style="font-size: 14px" id="by">Crée par <a class="panel" href="https://github.com/iPhoenix42/">iPhoenix42</a></span>';
echo '</div>';
echo '<img src="../Resources/CydiaIcon.png" style="vertical-align: middle" width="59" height="60"/>';
echo '';
echo '';
echo '</div>';
echo '<a';
echo '<p>';
echo '';
echo '<center>';
echo '<script type="text/javascript" src="http://www.abcompteur.com/live/?code=0/103/20116/6/1&ID=43497129754"></script><noscript>';
echo '<a href="http://www.abcompteur.com/">ABCompteur : compteur gratuit</a> </noscript> </center>';
echo '</a>';
echo '';
echo '';
echo '<p>C'est l'endroit où je pose mes derniers tweaks et partage la recherche.</p>';
echo '<p>Pour toutes questions, problèmes ou demandes, contactez moi sur:</p>';
echo '<p> </p>';
echo '';
echo '<p>- Sur Twitter:';
echo '<fieldset>';
echo '<a href="https://twitter.com/iPhoenix42">iPhoenix42   <img border="0"  src="../Resources/TwitterLogo.png" width="25" height="25"</a>';
echo '</div></a>';
echo '</fieldset>';
echo '';
echo '<p>- Sur Telegram:';
echo '<fieldset>';
echo '<a href="https://t.me/Apple_Jailbreak_Aide_Actu_FR">iPhoenix42   <img border="0"  src="../Resources/TelegramIcone.png" width="30" height="30"</a>';
echo '</div></a>';
echo '</fieldset>';
echo '';
echo '<p>- Sur Discord:';
echo '<fieldset>';
echo '<a href="https://discordapp.com/channels/@iPhoenix42">iPhoenix42   <img border="0"  src="../Resources/DiscordLogo.png" width="30" height="30"</a>';
echo '</div></a>';
echo '</fieldset>';
echo '';
echo '<p>- Mon site personnel:';
echo '<fieldset>';
echo '<a href="https://audrisrichard.wixsite.com/lesbonstuyaux">Audris les bons tuyaux   <img border="0"  src="../Resources/Site.png" width="30" height="30"</a>';
echo '</div></a>';
echo '</fieldset>';
echo '';
echo '';
echo '<block>';
echo '<p><strong><center>Mon repo iOS personnel</center></strong></p>';
echo '<p>Voici la source qui permettra d'ajouter mes tweak de ma source:</p>';
echo '<p>- <a href="cydia://url/https://cydia.saurik.com/api/share#?source=https://https://iphoenix42.github.io/repo.ios/">Ajouter à Cydia';
echo '</p></a>(SI TU UTILISES CYDIA)</p>';
echo '<p></p>';
echo '<p>- <a href="sileo://source/https://iphoenix42.github.io/repo.ios/">Ajouter à Sileo';
echo '<p></a>(SI TU UTILISES SILEO)</p>';
echo '</a>';
echo '<p></p>';
echo '<p>- <a href="installer://source/https://iphoenix42.github.io/repo.ios/">Ajouter à Installer 5';
echo '</p></a>(SI TU UTILISES INSTALLER 5)</a>';
echo '</p>';
echo '';
echo '<block>';
echo '<p><strong><center>Mon repo TvOS personnel</center></strong></p>';
echo '<p>Voici le lien de ma source qui permettra d'ajouter mes tweak de ma source:</p>';
echo '<a href="cydia://url/https://cydia.saurik.com/api/share#?source=https://https://iphoenix42.github.io/repo.tvos/"> → Ajouter à NITO TV';
echo '</p></a>(SI TU UTILISES UNE APPLE TV 4 OU 4K)</p>';
echo '<p></p>';
echo '</block>';
echo '</a>';
echo '<center><label><strong>Clique pour jailbreak</strong></label></center>';
echo '<p>';
echo '<label><center> À autoriser dans : <label></center>';
echo '<label><center>"Réglages -> Général -> Profils" </center></label>';
echo '';
echo '<p>';
echo '<label><center> Apps : </center></label>';
echo '';
echo '<fieldset>';
echo '<a href="itms-services://?action=download-manifest&url=https://iphoenix42.github.io/repo.ios/download/1_EtasonJB8_fr_FR.plist">';
echo '<img class="icon" src="../Resources/eston.png" width="58" height="58"><div>';
echo '<label>EtasonJB (iOS8.4/8.4.1)</label>';
echo '</div></a>';
echo '</fieldset>';
echo '<fieldset>';
echo '<a href="itms-services://?action=download-manifest&url=https://iphoenix42.github.io/repo.ios/download/2_Pangu9_fr_FR.plist">';
echo '<img class="icon" src="../Resources/Pangu.png" width="58" height="58"><div>';
echo '<label>Pangu (iOS9.2/9.3.3-64 bit)</label>';
echo '</div></a>';
echo '</fieldset>';
echo '<fieldset>';
echo '<a href="itms-services://?action=download-manifest&url=https://iphoenix42.github.io/repo.ios/download/3_Phoenix9_fr_FR.plist">';
echo '<img class="icon" src="../Resources/Phoenix.png" width="58" height="58"><div>';
echo '<label>Phoenix (iOS9.3.5/9.3.6) </label>';
echo '</div></a>';
echo '</fieldset>';
echo '<fieldset>';
echo '<a href="itms-services://?action=download-manifest&url=https://iphoenix42.github.io/repo.ios/download/4_Doublehelix10_fr_FR.plist">';
echo '<img class="icon" src="../Resources/H3lix.png" width="58" height="58"><div>';
echo '<label>Double H3lix (iOS10/10.3.3)</label>';
echo '</div></a>';
echo '</fieldset>';
echo '<fieldset>';
echo '<a href="itms-services://?action=download-manifest&url=https://iphoenix42.github.io/repo.ios/download/5_electra11_fr_FR.plist">';
echo '<img class="icon" src="../Resources/Electra.png" width="58" height="58"><div>';
echo '<label>Electra (iOS11/11.4)</label>';
echo '</div></a>';
echo '</fieldset>';
echo '<fieldset>';
echo '<a href="itms-services://?action=download-manifest&url=https://iphoenix42.github.io/repo.ios/download/6_chimera12_fr_FR.plist">';
echo '<img class="icon" src="../Resources/Chimera.png" width="58" height="58"><div>';
echo '<label>Chimera (iOS12/12.4)</label>';
echo '</div></a>';
echo '</fieldset>';
echo '<fieldset>';
echo '<a href="itms-services://?action=download-manifest&url=https://iphoenix42.github.io/repo.ios/download/7_unc0ver13_fr_FR.plist">';
echo '<img class="icon" src="../Resources/Unc0ver.png" width="58" height="58"><div>';
echo '<label>Unc0ver (iOS11.0/13.3)</label>';
echo '</div></a>';
echo '</fieldset>';
echo '<p>';
echo '<fieldset>';
echo '<p><strong><center>En avant les tweaks!</center></strong></p>';
echo '<p>Voici un lien, en français, fait par mes mains, pour vous montrer comment on creer un deb pour votre futur source jailbreak: </p>';
echo '';
echo '<a';
echo 'class="panel" href="https://github.com/iPhoenix42/repo.ios/blob/master/Creer%20tweak--Source.doc/"><strong><center>Acces au tuto</center></p></strong>';
echo '</p></a>';
echo '<p></p>';
echo '</panel>';
echo '<fieldset class="footer">';
echo '<label>';
echo 'Copyright © 2020 iPhoenix42';
echo '</label>';
echo '</fieldset>';
echo '</panel>';
echo '</body>';
echo '</html>';
echo '';
?>
